services:
  - type: web
    name: weather-forecast-app
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn weather_project.wsgi"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: weather_project.settings
      - key: PYTHON_VERSION
        value: 3.11
